const fs = require('fs');

try {
  const html = fs.readFileSync('c:/Users/Admin/OneDrive/Desktop/As-Dance/landing.html', 'utf8');
  
  const styleStart = html.indexOf('<style>');
  const styleEnd = html.indexOf('</style>');
  
  if (styleStart !== -1 && styleEnd !== -1) {
    let css = html.substring(styleStart + 7, styleEnd);
    
    // Prefix basic selectors
    css = css.replace(/(?:^|\n)\s*body\s*\{/g, '\n.landing-promo-wrapper {');
    css = css.replace(/(?:^|\n)\s*html\s*\{/g, '\n.landing-promo-wrapper {');
    css = css.replace(/(?:^|\n)\s*h1,\s*\n\s*h2,\s*\n\s*h3,\s*\n\s*h4\s*\{/g, '\n.landing-promo-wrapper h1, .landing-promo-wrapper h2, .landing-promo-wrapper h3, .landing-promo-wrapper h4 {');
    css = css.replace(/(?:^|\n)\s*a\s*\{/g, '\n.landing-promo-wrapper a {');
    css = css.replace(/(?:^|\n)\s*ul\s*\{/g, '\n.landing-promo-wrapper ul {');
    css = css.replace(/(?:^|\n)\s*button\s*\{/g, '\n.landing-promo-wrapper button {');
    css = css.replace(/(?:^|\n)\s*section\s*\{/g, '\n.landing-promo-wrapper section {');
    
    fs.writeFileSync('c:/Users/Admin/OneDrive/Desktop/As-Dance/frontend/src/ui/landing-promo.css', "/* CSS GENERATED BY NODE */\n" + css);
    console.log("SUCCESS! Wrote CSS of length " + css.length);
  } else {
    console.log("FAILED to find <style>");
  }
} catch (e) {
  console.error("ERROR", e);
}
